### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by ryangjchandler** [php-rust-tools/parser#152]
Something I've experimented with a little bit is a reflection API provided by the parser. 

You provide it a generated AST (or multiple ASTs) and the struct is able to traverse the AST to search for function declarations, classes, etc. 

You would then be able to call methods on the struct to find a particular class, function, get type information, params etc. 

This would do a lot of heavy lifting for static analysis tools, dead code finders, interpreters etc.

**Comment by azjezz** [comment]
reflection can be a whole different project in it's own repository.

it is possible to build a reflection system from AST, see https://github.com/Roave/BetterReflection for reference.

**Comment by ryangjchandler** [comment]
yeah, whether its part of this repo or not, doesn't bother me. just noting down ideas surrounding the parser

**Comment by ryangjchandler** [comment]
Not related to parser, closing.
