### ISSUE TITLE
Allow to choose language level

### ISSUE THREAD

**Issue by shyim** [php-rust-tools/parser#207]
For linting case It would be nice if you could specify the language level like PHP 8.1 and any new language features are a parsing error.

Background:

I have an [AWS Lambda](https://github.com/FriendsOfShopware/aws-php-syntax-checker-lambda) to check the PHP Syntax of an uploaded zip. It would make it much simpler. If I could use this I would get rid of bundeling each PHP version into that lambda 😅

**Comment by azjezz** [comment]
that is something definitely to consider for the future, but for now, we just want to be able to parse everything 8.0+.

**Comment by ryangjchandler** [comment]
I think I'm going to close this and potentially revisit in the future. Right now though, I'm only interested in supporting PHP 8.0+. The added overhead of tracking feature flags etc for older versions isn't something I want to deal with right now.
