### ISSUE TITLE
remove utility nodes

### ISSUE THREAD

**Issue by azjezz** [php-rust-tools/parser#252]
the following ast nodes should be removed: https://github.com/php-rust-tools/parser/blob/main/src/parser/ast/utils.rs#L7-L28

every other node that uses these nodes should store the inner and surrounding token(s) span(s) itself, instead of relying on these generic nodes.

the generic nodes result in a pretty messy schema.

the utility functions in `crate::parser::internal::utils` module, should return `(Span, T, Span)` or `(T, Span)` instead of returning the generic node.

the caller should always store the spans in the generated node, as we want the ast ( which is really cst at this point ) to represent the code as much as possible.

---

Note: the `CommaSeparated` node shouldn't be removed, until we figure out a better way of dealing with those.

**Comment by azjezz** [comment]
cc @drupol 😄

**Comment by drupol** [comment]
Trying... I won't promise anything!
