### ISSUE TITLE
Project communication channel

### ISSUE THREAD

**Issue by KennedyTedesco** [php-rust-tools/parser#257]
Do we have a Discord or Slack channel set up where we can discuss ideas, share updates, and collaborate on tasks?

**Comment by williamdes** [comment]
Or a Matrix room ?
That could bridge Discord for example.
I do not recommend Slack due to it's cost for small projects.

**Comment by ryangjchandler** [comment]
I'll look at sorting out a Discord server in the new year :^)

**Comment by ryangjchandler** [comment]
Discord invite link here: https://discord.gg/mCTx877dsV
