### ISSUE TITLE
empty is not a function

### ISSUE THREAD

**Issue by azjezz** [php-rust-tools/parser#258]
currently, `empty($x)` is parsed as a function call, this should have it's own node in the ast just like `echo`, `isset`, `unset`, `print`, `die`..etc.

**Comment by KennedyTedesco** [comment]
@azjezz Is this the right direction and what you're expecting?

https://github.com/KennedyTedesco/parser/commit/8df2d73e638c94bd84f374d031c91bd65b3161a3

If so, I can work on this and send a PR. =D If not, I'll skip and study the subject a bit more.

**Comment by azjezz** [comment]
yes, be we also need to keep span for of the keyword

**Comment by KennedyTedesco** [comment]
I've done it this way:

https://github.com/KennedyTedesco/parser/commit/588e4eaa707ae3176130f4781720f74e5ef0997c

I think that's it, right?

I'll start to work on the others ones. :blush:

**Comment by azjezz** [comment]
Yes, looking at the code `(` and `)` also need to be there, you can open a PR for this :)

also, it seems echo, eval, and die are also missing the span of the parenthesis and keywords.

**Comment by KennedyTedesco** [comment]
Updated version: https://github.com/KennedyTedesco/parser/commit/d557212d2129276c3ca8e318799daddb82d3b1c1

I think I got it right :)

I'll continue working on it.

**Comment by azjezz** [comment]
yep! perfect :D
