### ISSUE TITLE
Visitor example

### ISSUE THREAD

**Issue by DMS-CPP** [php-rust-tools/parser#271]
Could you please provide a short example for how to use `traverser::Visitor`? I'm not sure how to match for `&mut dyn Node` cases when traversing the AST

**Comment by ryangjchandler** [comment]
Hey @DMS-CPP, what sort of thing are you trying to do with the `Visitor` exactly? I might be able to provide some more specific help.

The README / docs need updating once I've tagged another release.

**Comment by DMS-CPP** [comment]
I'm just not sure how I could traverse the AST with the Visitor and call different functions for some kind of Nodes. Some practical examples for Visitor would be very helpful. For example if it could be used to find a pattern and modify the AST

**Comment by ryangjchandler** [comment]
The crate provides a `downcast()` method and `downcast_mut()` method which can be used to convert the trait object into a struct or enum.

I'll provide some examples when I'm at my laptop as part of the README.
